spring:
 jwt:
   secret-key: 753778214125442A472D4B6150645367566B59703373367639792F423F452848
 springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

 banner:
   location:
    classpath:/banner.txt
 mail:
    host: smtp.gmail.com
    port: 587
    username: b49582653@gmail.com
    password: djzk znet jpmd novl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
 application:
    name: FastFood_App
 datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 12345
    url: jdbc:postgresql://localhost:5432/fast_food
 jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080


